[workspace]
members = [
    "core",
    "derive",
    "wrappers",
    "utils/hash_db",
    "utils/trie_db",
    "utils/trie_map",
    "utils/slot_db",
]
resolver = "2"

[workspace.dependencies]
ruc = "4.2.0"
rand = "0.8.5"
once_cell = "1.13.1"
parking_lot = "0.12.1"

bcs = { version = "0.1.5" }
rmp-serde = { version = "1.1.1" }
serde_json = { version = "1.0.87" }
serde = { version = "1.0.136", features = ["derive"] }

threadpool = "1.8.1" # used in a background cleaner

primitive-types-0-12 = { package = "primitive-types", version = "0.12", default-features = false }
primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

rocksdb = { version = "0.21.0", default-features = false }
sled = { package = "vsdbsled", version = "0.34.7-p1" }

sp-trie = "22.0"
sp-trie-db = { package = "trie-db", version = "0.27.1" }
hash-db = "0.16.0"
keccak-hasher = "0.16.0"

vsdb = { path = "wrappers", version = "0.57.0", default-features = false }
vsdb_core = { path = "core", version = "0.56.0", default-features = false }
vsdb_derive = { path = "derive", version = "0.53.0" }

vsdb_trie_db = { path = "utils/trie_db", version = "0.10.0", default-features = false }
vsdb_hash_db = { path = "utils/hash_db", version = "0.9.0", default-features = false }
