[package]
name = "vsdb"
version = "0.37.0"
authors = ["fanhui.x@gmail.com"]
edition = "2021"
description = "A stuctured DB with some 'Git-like' features, originally designed for blockchain scene."
homepage = "https://github.com/ccmlm/vsdb"
repository = "https://github.com/ccmlm/vsdb"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "MIT"

[dependencies]
ruc = "1.0.7"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
parking_lot = "0.12.0"

primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

msgpack = { package = "rmp-serde", version = "1.1.0", optional = true }
bcs = { version = "0.1.3", optional = true }

# vsdb_derive = { path = "../vsdb_derive", optional = true }
vsdb_derive = { version = "0.35.3", optional = true }

blake3 = { version = "1.3.1", optional = true }

rocksdb = { version = "0.18.0", default-features = false, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-p1", features = ["io_uring"], optional = true }

[target.'cfg(not(target_os = "linux"))'.dependencies]
sled = { package = "vsdbsled", version = "0.34.7-p1", optional = true }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"]}
hex = "0.4.3"
rand = "0.8.5"

[features]
default = ["rocks_engine", "msgpack_codec", "derive", "compress"]

derive = ["vsdb_derive"]
compress = ["sled?/compression", "rocksdb?/lz4"]

rocks_engine = ["rocksdb"]
sled_engine = ["sled"]

msgpack_codec = ["msgpack"]
bcs_codec = ["bcs"]

hash= ["blake3"]

[[bench]]
name = "bench_main"
harness = false

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
incremental = false
overflow-checks = false

[profile.bench]
incremental = false
overflow-checks = false

[[example]]
name = "blockchain_state"

[[example]]
name = "web_server"

[[example]]
name = "derive_vs"
