[workspace]
members = [
    "core",
    "derive",
    "wrappers",
    "utils/hash_db",
    "utils/trie_db",
    "utils/trie_map",
    "utils/slot_db",
]
resolver = "2"

[workspace.dependencies]
ruc = "5.0.10"
rand = "0.8.5"
once_cell = "1.13.1"
parking_lot = "0.12.1"

bcs = { version = "0.1.5" }
rmp-serde = { version = "1.1.1" }
serde_json = { version = "1.0.87" }
serde = { version = "1.0.136", features = ["derive"] }

threadpool = "1.8.1" # used in a background cleaner

primitive-types-0-12 = { package = "primitive-types", version = "0.12", default-features = false }
primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false }

parity-db = "0.4.10"
rocksdb = { version = "0.21.0", default-features = false }

keccak-hasher = "0.16.0"
hash-db = "0.16.0"
trie-db = "0.27.1"
reference-trie = "0.29.1"

# vsdb = { git = "https://github.com/rust-util-collections/vsdb", branch = "feat-full-trie", default-features = false }
# vsdb_core = { git = "https://github.com/rust-util-collections/vsdb", branch = "feat-full-trie", default-features = false }
vsdb = { path = "wrappers", version = "0.61.0", default-features = false }
vsdb_core = { path = "core", version = "0.61.0", default-features = false }
vsdb_derive = { path = "derive", version = "0.53.0" }

# vsdb_trie_db = { git = "https://github.com/rust-util-collections/vsdb", branch = "feat-full-trie", default-features = false }
# vsdb_hash_db = { git = "https://github.com/rust-util-collections/vsdb", branch = "feat-full-trie", default-features = false }
vsdb_trie_db = { path = "utils/trie_db", version = "0.20.0", default-features = false }
vsdb_hash_db = { path = "utils/hash_db", version = "0.20.0", default-features = false }

[patch.crates-io]
keccak-hasher = { git = "https://github.com/rust-util-collections/trie", tag = "v0.27.1-full-history" }
hash-db = { git = "https://github.com/rust-util-collections/trie", tag = "v0.27.1-full-history" }
trie-db = { git = "https://github.com/rust-util-collections/trie", tag = "v0.27.1-full-history" }
reference-trie = { git = "https://github.com/rust-util-collections/trie", tag = "v0.27.1-full-history" }
