[package]
name = "vsdb"
version = "0.48.9"
authors = ["dafanhui@163.com", "hui.fan@mail.ru"]
edition = "2021"
description = "A stuctured DB with some 'Git-like' features, mainly used in blockchain projects."
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb/tree/master/wrappers"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "GPL-3.0"

[dependencies]
ruc = "4.0.0"
once_cell = "1.13.1"
serde = { version = "1.0.136", features = ["derive"] }
parking_lot = "0.12.1"

serde_json = { version = "1.0.87", optional = true }
bcs = { version = "0.1.4", optional = true }

vsdb_core = { path = "../core", version = "0.48.7" }

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4.0"
rand = "0.8.5"

[features]
default = ["sled_engine", "json_codec", "derive"]

compress = ["vsdb_core/compress"]

sled_engine = ["vsdb_core/sled_engine"]
rocks_engine = ["vsdb_core/rocks_engine"]

sled_compress = ["vsdb_core/sled_compress"]
rocks_compress = ["vsdb_core/rocks_compress"]

bcs_codec = ["bcs"]
json_codec = ["serde_json"]

derive = ["vsdb_core/derive"]
extra_types = ["vsdb_core/extra_types"]

[[bench]]
name = "exec"
harness = false

[[example]]
name = "derive_vs"

[[example]]
name = "web_server"

[[example]]
name = "blockchain_state"
