[package]
name = "vsdb"
version = "0.46.0"
authors = ["dafanhui@163.com", "hui.fan@mail.ru"]
edition = "2021"
description = "A stuctured DB with some 'Git-like' features, mainly used in blockchain projects."
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb/tree/master/wrappers"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "GPL-3.0"

[dependencies]
ruc = "2.0.0"
once_cell = "1.13.1"
serde = { version = "1.0.136", features = ["derive"] }
parking_lot = "0.12.1"

msgpack = { package = "rmp-serde", version = "1.1.0", optional = true }
bcs = { version = "0.1.3", optional = true }

# vsdb_core = { path = "../core" }
vsdb_core = "0.46.0"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"]}
hex = "0.4.3"
rand = "0.8.5"

[features]
default = ["sled_engine", "msgpack_codec", "derive"]

sled_engine = ["vsdb_core/sled_engine"]
rocks_engine = ["vsdb_core/rocks_engine"]

bcs_codec = ["bcs"]
msgpack_codec = ["msgpack"]

derive = ["vsdb_core/derive"]
compress = ["vsdb_core/compress"]
extra_types = ["vsdb_core/extra_types"]

[[bench]]
name = "exec"
harness = false

[[example]]
name = "derive_vs"

[[example]]
name = "web_server"

[[example]]
name = "blockchain_state"
