[package]
name = "slot_db"
version = "0.1.0"
edition = "2021"
keywords = ["timestamp", "slot", "database", "web"]
license = "MIT"
authors = ["hui.fan@mail.ru"]
description = "A skip-list like timestamp DB"
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb"

[dependencies]
ruc = { workspace = true }
vsdb = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["rocks_engine"]

sled_engine = ["vsdb/sled_engine"]
rocks_engine = ["vsdb/rocks_engine"]

bcs_codec = ["vsdb/bcs_codec"]
json_codec = ["vsdb/json_codec"]
msgpack_codec = ["vsdb/msgpack_codec"]
