[package]
name = "vsdb_core"
version = "0.56.2"
authors = ["hui.fan@mail.ru"]
edition = "2021"
description = "A stuctured DB with some 'Git-like' features, mainly used in blockchain projects."
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb/tree/master/core"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "GPL-3.0"

[dependencies]
ruc = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }

threadpool = { workspace = true } # used in a background cleaner

primitive-types-0-12 = {  workspace = true, optional = true }
primitive-types-0-11 = { workspace = true, optional = true }
primitive-types-0-10 = { workspace = true, optional = true }

vsdb_derive = { workspace = true, optional = true }

sled = { workspace = true, optional = true }
rocksdb = { workspace = true, optional = true }

[dev-dependencies]
bcs = "0.1.4"
hex = "0.4.3"
criterion = "0.4.0"

[features]
default = ["rocks_engine", "compress"]

vs = ["vsdb_derive"] # the switch of all versioned APIs

compress = ["sled_compress", "rocks_compress"]

sled_engine = ["sled"]
rocks_engine = ["rocksdb"]

sled_compress = ["sled?/compression"]
rocks_compress = ["rocksdb?/zstd"]

extra_types = ["primitive-types-0-12", "primitive-types-0-11", "primitive-types-0-10"]

[[bench]]
name = "basic"
harness = false

[[bench]]
name = "versioned"
harness = false
