[package]
name = "vsdb_core"
version = "0.50.2"
authors = ["dafanhui@163.com", "hui.fan@mail.ru"]
edition = "2021"
description = "A stuctured DB with some 'Git-like' features, mainly used in blockchain projects."
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb/tree/master/core"
keywords = ["git", "leveldb", "rocksdb", "version", "vcs"]
categories = ["database-implementations", "data-structures", "algorithms", "caching"]
license = "GPL-3.0"

[dependencies]
ruc = "4.0.0"
once_cell = "1.13.1"
serde = { version = "1.0.136", features = ["derive"] }
parking_lot = "0.12.1"
rand = "0.8.5"

blake3 = "1.3.1"
hash-db = "0.16.0"
triehash = "0.8.4"
hash256-std-hasher = "0.15.2"

threadpool = "1.8.1" # used in a background cleaner

primitive-types-0-12 = { package = "primitive-types", version = "0.12", default-features = false, optional = true }
primitive-types-0-11 = { package = "primitive-types", version = "0.11", default-features = false, optional = true }
primitive-types-0-10 = { package = "primitive-types", version = "0.10", default-features = false, optional = true }

# vsdb_derive = { path = "../derive", optional = true }
vsdb_derive = { version = "0.45.0", optional = true }

sled = { package = "vsdbsled", version = "0.34.7-p1", optional = true }
# sled = { package = "vsdbsled", version = "0.34.7-p1", features = ["io_uring"], optional = true }
rocksdb = { version = "0.20.1", default-features = false, optional = true }

[dev-dependencies]
bcs = "0.1.4"
criterion = "0.4.0"
hex = "0.4.3"

[features]
default = ["sled_engine", "derive"]

derive = ["vsdb_derive"]

compress = ["sled_compress", "rocks_compress"]

sled_engine = ["sled"]
rocks_engine = ["rocksdb"]

sled_compress = ["sled?/compression"]
rocks_compress = ["rocksdb?/lz4"]

extra_types = ["primitive-types-0-12", "primitive-types-0-11", "primitive-types-0-10"]

[[bench]]
name = "exec"
harness = false
