[package]
name = "vsdb_trie_db"
version = "0.10.0"
edition = "2021"
keywords = ["mpt", "trie", "database", "blockchain"]
license = "MIT"
authors = ["hui.fan@mail.ru"]
description = "An out-of-box wraper of the `trie_db` crate"
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb"

[dependencies]
serde = { workspace = true }
sp-trie = { workspace = true }

ruc = { workspace = true }
vsdb = { workspace = true }
vsdb_hash_db = { workspace = true }

[features]
default = ["rocks_engine"]

sled_engine = ["vsdb_hash_db/sled_engine"]
rocks_engine = ["vsdb_hash_db/rocks_engine"]

bcs_codec = ["vsdb_hash_db/bcs_codec"]
json_codec = ["vsdb_hash_db/json_codec"]
msgpack_codec = ["vsdb_hash_db/msgpack_codec"]
